[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/portal_equipe.html"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "cnes-360-portal"

[services.variables]
NODE_ENV = "production"
PORT = "8080"

[[services.ports]]
port = 8080
handlers = ["http"]
